### PR TITLE
Typo fix for Archstair_Improvement9

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
Hey @paullee0 Can you take a look at this PR and see if it makes sense. I made it against the PR you just got merged in to FreeCAD master. I guess can just create a new branch and add it to your next Archstair PR.

**Comment by paullee0** [comment]
Hi, thanks for the comments!  and Yes good to merge!  Good to have peoples have another look especially for pyhton newbie like me.

Wondering what best should I do for this/similar situation, appreciate if you can give more hints :)
- I am working on my local pc changes to the same file
- For a few fixes I can copy & paste into my local file, should the better way be kind of 'rebase' onto this one?
- Or should I press button 'Merge pull request', then it would create a PR to FreeCAD/FreeCAD and I pull and rebase would merge this into my file which is being update in parallel also?

**Comment by luzpaz** [comment]
@paullee0 are you using git in the command line or a git GUI ?

**Comment by paullee0** [comment]
Git command on Fedora 27 
(basic commands following [https://forum.freecadweb.org/viewtopic.php?f=10&t=23204&sid=34b01eb4b2161acc2391a6c86ef05233&start=10](url) )

**Comment by paullee0** [comment]
Hi, I just click the Merge button here....

... not sure how I request a PR from here to FreeCAD/FreeCAD....?

**Comment by luzpaz** [comment]
Note: You already submitted `paullee0:ArchStairs_Improvement_9` as a PR. So don't forget when you create a new PR to make sure these commits are in there. :wink:

**Comment by paullee0** [comment]
I go to
https://github.com/FreeCAD/FreeCAD/pulls

and do not see it there ...?

**Comment by paullee0** [comment]
> Note: You already submitted `paullee0:ArchStairs_Improvement_9` as a PR. So don't forget when you create a new PR to make sure these commits are in there. wink

I make a PR at FreeCAD/FreeCAD... not sure it is correct... seem there is 5 commits (4 duplicate previous?)

**Comment by luzpaz** [comment]
What you did is resubmitted the same PR which was already merged :man_facepalming: 
No problem. You can close the PR. 
Make a new branch off of Master, `checkout` the new branch, and then `cherrypick` the commit that I submitted to you in to the new branch. 
I know how to do this in GitKraken, see https://support.gitkraken.com/working-with-commits/cherrypick

**Comment by paullee0** [comment]
OK, thanks closed it at FreeCAD/FreeCAD
... unfortunately noGitKraken in Fedora (official)

... I'll see how your PR can be added in my local PC repository by Git command?
... Or can I do it here it GitHub?

**Comment by paullee0** [comment]
Thanks for the commands and link!

Save me lot of time in reading understanding the basic!

**Comment by luzpaz** [comment]
What you just did is pulled the commit from that previous branch in to your new one

**Comment by paullee0** [comment]
Hi, some problem and queries -

1. Cherry-pick return below error
[paullee@f27--40g-95g-hdd FreeCAD]$ git cherry-pick d343948
error: commit d343948af765718c56ad4440e1ef8456a886cc5b is a merge but no -m option was given.
fatal: cherry-pick failed

2. After cherry-pick works, at some points, still need to 'catch up' and 'rebase' like below?-

"Catch up my newBranch with upstream/master (the "real" master):
  *git checkout master
  *git fetch upstream
  *git merge upstream/master
  *git checkout newBranchName
  git rebase master"

3. Do you mind adding the 'cherry-pick' procedures to the discussion thread?
[https://forum.freecadweb.org/viewtopic.php?f=10&t=23204&sid=34b01eb4b2161acc2391a6c86ef05233&start=10](url)

**Comment by paullee0** [comment]
Hi, studying and trial and error for a few time, then"

`[paullee@f27--40g-95g-hdd FreeCAD]$ git cherry-pick -m 1 d343948
[ArchStairs_Improvement_10 4a4bdb209] Merge pull request #1 from luzpaz/ArchStairs_Improvement_9
 Author: paul <40677073+paullee0@users.noreply.github.com>
 Date: Thu Oct 4 03:30:04 2018 +0800
 1 file changed, 6 insertions(+), 6 deletions(-)
`

So, now if with other commits I want to push to Upstream, I need to fetch upstream (instead of fetch only) and merge and rebase etc.  right?

> Catch up my newBranch with upstream/master (the "real" master) 
  git checkout master
  git fetch upstream
  git merge upstream/master
  git checkout newBranchName
  git rebase master

Send my changes to my github:
  git checkout newBranchName
  git push origin

Thanks for the hints!

**Comment by paullee0** [comment]
Ok, I seems to have made a few commit and integrate with yours and Pull Request to Upstream FreeCAD.

**Pull request merged**
